### ISSUE TITLE
VSCode Extension - Getting started - Download Sample App bug

### ISSUE THREAD

**Issue by bolt-io** [microsoft/vscode-ms-entra#9]
I have three External ID for Customer tenants and when using the quick start download a sample app it asks to select a tenant but then proceeds to create 3 app registrations and 3 auth flows inside that selected tenant.

![image](https://github.com/microsoft/vscode-ms-entra/assets/10209663/621e7691-733a-4e4d-91c9-02cf6eb47604)

**Comment by wainaina** [comment]
Hello. The tree view only displays the existing resources. The sample download process does not involve application or authentication flow creation. 

Had you created these resources earlier? 

Also, please share the version of the extension you are currently using. Thanks.

**Comment by bolt-io** [comment]
It has to involve app and auth flow creation as I did not create these and the sample came preloaded with the correct client ID and a generated secret - which I also did not create 👀 

The secret description does allude to it being from quick start!
App reg 1
![image](https://github.com/microsoft/vscode-ms-entra/assets/10209663/d5f121c2-7ba8-4301-a146-d9b88e0828f9)

App reg 2
![image](https://github.com/microsoft/vscode-ms-entra/assets/10209663/81b44684-b07a-48b7-a230-e01326b23aea)

App reg 3
![image](https://github.com/microsoft/vscode-ms-entra/assets/10209663/0d4bf099-f763-433e-a6c2-82b2411515f6)



v0.1.6

**Comment by mpminayo** [comment]
Hello there. I tested this on version 0.1.6 and other subsequent releases. I was unable to reproduce this issue. However, I suspect that the issue may have arisen during the setup of sign-in and branding. Had you made any updates to an already configured company branding through the 'Set up sign in' step on the walkthrough or via the 'Configure sign-in experience' in the explorer view? These actions may inadvertently result in creation of multiple authentication flows and applications.

Also, client secret is automatically generated in the background as it is required by samples such as Python and .NET Core. The displayName in passwordCredentials is simply a string used internally during the secret creation process.
